context:
  name: essdiffraction
  version: "26.10.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essdiffraction-${{ version }}.tar.gz
  sha256: 1945fddf8947c4b1cb8672337f1e702915120fee0bd2d36be02e130b1ebb4675

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - python-graphviz >=0.20
    - essreduce >=26.6.0
    - mcstastox >=0.0.11
    - numpy >=2
    - plopp >=26.5.0
    - tof >=25.12.0
    - ncrystal >=4.1.0
    - ncrystal-extra >=4.1.0
    - spglib >=2.0.0,!=2.7

tests:
  - python:
      imports:
        - ess.diffraction
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
about:
  summary: Diffraction data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/ess/tree/main/packages/essdiffraction
  homepage: https://scipp.github.io/ess/diffraction/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
